//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEMS.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Models;
    [MetadataType(typeof(Emp_Progress))]

    public partial class emp_progresses
    {
        public int emp_progress_id { get; set; }
        public string emp_progress_working_hrs { get; set; }
        public string emp_progress_month_year { get; set; }
        public int emp_progress_nopay_days { get; set; }
        public int emp_progress_status { get; set; }
        public int emp_id { get; set; }
        public int project_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual project project { get; set; }
    }
}
