//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEMS.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Models;
    [MetadataType(typeof(Emp_task_ref))]

    public partial class emp_task_ref
    {
        public int emp_task_ref_id { get; set; }
        public int emp_id { get; set; }
        public int task_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual task task { get; set; }
    }
}
