//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEMS.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Models;
    [MetadataType(typeof(Employee))]

    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.emp_progresses = new HashSet<emp_progresses>();
            this.emp_task_ref = new HashSet<emp_task_ref>();
        }
    
        public int emp_id { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public string emp_nic { get; set; }
        public string emp_dob { get; set; }
        public string emp_gender { get; set; }
        public string emp_address { get; set; }
        public string emp_mobile { get; set; }
        public string emp_designation { get; set; }
        public string emp_work_started_date { get; set; }
        public int emp_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_progresses> emp_progresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_task_ref> emp_task_ref { get; set; }
    }
}
