//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEMS.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Models;
    [MetadataType(typeof(Project_progress))]

    public partial class project_progress
    {
        public int progress_id { get; set; }
        public int no_of_tasks { get; set; }
        public int days_remaining { get; set; }
        public int no_of_finished_tasks { get; set; }
        public int project_id { get; set; }
    
        public virtual project project { get; set; }
    }
}
